version: "3"
services:
  rabbitmq:
    container_name: rabbitmq-learning-container
    image: rabbitmq:3-management
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - 5672:5672
      - 15672:15672
